CREATE TABLE CLIENT(
   Email_Client VARCHAR(50),
   Nom_Client VARCHAR(50),
   Prenom_Client VARCHAR(50),
   Date_Naissance DATE,
   Telephone BIGINT,
   PRIMARY KEY(Email_Client)
);

CREATE TABLE PRODUIT(
   SKU_Produit VARCHAR(15),
   Code_Barre_EAN VARBINARY(13),
   Libelle_Produit VARCHAR(150),
   Description_Detaillee VARCHAR(500),
   Prix_de_vente_TTC DECIMAL(4,2),
   Categorie VARCHAR(30),
   Plateforme VARCHAR(20),
   Etat_Produit VARCHAR(10),
   Editeur_Marque VARCHAR(50),
   Date_Sortie_Officielle DATE,
   PRIMARY KEY(SKU_Produit)
);

CREATE TABLE MAGASIN(
   Id_MAGASIN COUNTER,
   Nom_Magasin VARCHAR(50),
   Ville VARCHAR(50),
   Code_Postal BIGINT,
   PRIMARY KEY(Id_MAGASIN)
);

CREATE TABLE PRECOMMANDE(
   Email_Client VARCHAR(50),
   Num_COMMANDE COUNTER,
   Date_Precommande DATETIME,
   Montant_Acompte DOUBLE,
   SKU_Produit VARCHAR(15) NOT NULL,
   PRIMARY KEY(Email_Client, Num_COMMANDE),
   FOREIGN KEY(Email_Client) REFERENCES CLIENT(Email_Client),
   FOREIGN KEY(SKU_Produit) REFERENCES PRODUIT(SKU_Produit) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CARTE_FIDELITE(
   Num_Carte_Fidelite VARCHAR(20),
   Point_Cumules BYTE,
   Statu_Carte VARCHAR(15),
   Email_Client VARCHAR(50) NOT NULL,
   PRIMARY KEY(Num_Carte_Fidelite),
   UNIQUE(Email_Client),
   FOREIGN KEY(Email_Client) REFERENCES CLIENT(Email_Client) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RECOMMANDER(
   SKU_Produit VARCHAR(15),
   SKU_Produit_1 VARCHAR(15),
   PRIMARY KEY(SKU_Produit, SKU_Produit_1),
   FOREIGN KEY(SKU_Produit) REFERENCES PRODUIT(SKU_Produit) ON DELETE CASCADE ON UPDATE CASCADE,
   FOREIGN KEY(SKU_Produit_1) REFERENCES PRODUIT(SKU_Produit) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ACHETER(
   Email_Client VARCHAR(50),
   SKU_Produit VARCHAR(15),
   Id_MAGASIN INT,
   Num_Ticket_Caisse VARCHAR(20),
   Date_Transaction DATE,
   Heure_Transaction TIME,
   Quantite_Achetee INT,
   Montant_Total_Ticket DECIMAL(6,2),
   PRIMARY KEY(Email_Client, SKU_Produit, Id_MAGASIN),
   FOREIGN KEY(Email_Client) REFERENCES CLIENT(Email_Client) ON DELETE CASCADE ON UPDATE CASCADE,
   FOREIGN KEY(SKU_Produit) REFERENCES PRODUIT(SKU_Produit) ON DELETE CASCADE ON UPDATE CASCADE,
   FOREIGN KEY(Id_MAGASIN) REFERENCES MAGASIN(Id_MAGASIN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE STOCKER(
   SKU_Produit VARCHAR(15),
   Id_MAGASIN INT,
   Quantite_en_stock INT,
   PRIMARY KEY(SKU_Produit, Id_MAGASIN),
   FOREIGN KEY(SKU_Produit) REFERENCES PRODUIT(SKU_Produit) ON DELETE CASCADE ON UPDATE CASCADE,
   FOREIGN KEY(Id_MAGASIN) REFERENCES MAGASIN(Id_MAGASIN) ON DELETE CASCADE ON UPDATE CASCADE
);
